# Generated by Django 2.2.16 on 2021-05-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycountmodel',
            name='count',
            field=models.IntegerField(db_column='count', default=0, verbose_name='Количество пришедших notify от сущности'),
        ),
        migrations.AlterField(
            model_name='notifycountmodel',
            name='last_update_datetime',
            field=models.DateTimeField(db_column='last_update_datetime', null=True, verbose_name='Дата и время последнего обновления'),
        ),
    ]
